"""Admin API endpoints for system configuration and user management."""

import logging
from datetime import datetime
from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel, Field
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.api.deps import get_current_superuser, get_db
from app.api.endpoints.tasks import TaskResponse
from app.db.models import SystemConfig, User, Strategy, AIReport
from app.db.session import AsyncSessionLocal
from app.core.constants import IMAGE_MODELS, REPORT_MODELS
from app.services.config_service import config_service

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/admin", tags=["admin"])


# Pydantic models for admin endpoints
class ConfigItem(BaseModel):
    """Configuration item model."""

    key: str = Field(..., description="Configuration key")
    value: str = Field(..., description="Configuration value")
    description: str | None = Field(None, description="Optional description")


class ConfigUpdateRequest(BaseModel):
    """Configuration update request model."""

    value: str = Field(..., description="New configuration value")
    description: str | None = Field(None, description="Optional description")


class AIModelsDefaultResponse(BaseModel):
    """Built-in report and image model lists (for admin UI reset-to-default)."""

    report_models: list[dict[str, str]] = Field(..., description="Built-in report models")
    image_models: list[dict[str, str]] = Field(..., description="Built-in image models")


# User management models
class UserResponse(BaseModel):
    """User response model for admin endpoints."""

    id: UUID = Field(..., description="User UUID")
    email: str = Field(..., description="User email")
    is_pro: bool = Field(..., description="Pro subscription status")
    is_superuser: bool = Field(..., description="Superuser status")
    subscription_id: str | None = Field(None, description="Subscription ID")
    plan_expiry_date: datetime | None = Field(None, description="Plan expiry date")
    daily_ai_usage: int = Field(..., description="Daily AI usage count")
    created_at: datetime = Field(..., description="Account creation date")
    strategies_count: int = Field(0, description="Number of strategies created by this user")
    ai_reports_count: int = Field(0, description="Number of AI reports generated by this user")


class UserUpdateRequest(BaseModel):
    """User update request model."""

    is_pro: bool | None = Field(None, description="Pro subscription status")
    is_superuser: bool | None = Field(None, description="Superuser status")
    plan_expiry_date: datetime | None = Field(None, description="Plan expiry date")


class UsersListResponse(BaseModel):
    """Paginated users list response."""
    users: list[UserResponse] = Field(..., description="List of users")
    total: int = Field(..., description="Total number of users (matching search if provided)")
    page: int = Field(..., description="Current page (0-indexed)")
    limit: int = Field(..., description="Items per page")


# Configuration endpoints
@router.get("/configs", response_model=list[ConfigItem])
async def get_all_configs(
    current_user: Annotated[User, Depends(get_current_superuser)],
) -> list[ConfigItem]:
    """
    Get all system configuration items.

    Requires superuser access.
    """
    try:
        async with AsyncSessionLocal() as session:
            result = await session.execute(select(SystemConfig))
            configs = result.scalars().all()

            return [
                ConfigItem(
                    key=config.key,
                    value=config.value,
                    description=config.description,
                )
                for config in configs
            ]
    except Exception as e:
        logger.error(f"Error fetching configs: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to fetch configs",
        )


@router.get("/configs/{key}", response_model=ConfigItem)
async def get_config(
    key: str,
    current_user: Annotated[User, Depends(get_current_superuser)],
) -> ConfigItem:
    """
    Get a specific configuration item.

    Requires superuser access.
    """
    try:
        value = await config_service.get(key)
        description = await config_service.get_description(key)

        return ConfigItem(key=key, value=value, description=description)
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Config key '{key}' not found",
        )
    except Exception as e:
        logger.error(f"Error fetching config {key}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to fetch config",
        )


@router.put("/configs/{key}", response_model=ConfigItem)
async def update_config(
    key: str,
    request: ConfigUpdateRequest,
    current_user: Annotated[User, Depends(get_current_superuser)],
) -> ConfigItem:
    """
    Update a configuration item.

    Requires superuser access.
    """
    try:
        await config_service.set(
            key, request.value, description=request.description, updated_by=current_user.id
        )

        return ConfigItem(
            key=key, value=request.value, description=request.description
        )
    except Exception as e:
        logger.error(f"Error updating config {key}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to update config",
        )


@router.get("/ai-models-default", response_model=AIModelsDefaultResponse)
async def get_ai_models_default(
    current_user: Annotated[User, Depends(get_current_superuser)],
) -> AIModelsDefaultResponse:
    """
    Return built-in report and image model lists (for admin UI).
    Stored in DB keys ai_report_models_json / ai_image_models_json override these when set.
    """
    return AIModelsDefaultResponse(
        report_models=list(REPORT_MODELS),
        image_models=list(IMAGE_MODELS),
    )


@router.delete("/configs/{key}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_config(
    key: str,
    current_user: Annotated[User, Depends(get_current_superuser)],
) -> None:
    """
    Delete a configuration item.

    Requires superuser access.
    """
    try:
        await config_service.delete(key)
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Config key '{key}' not found",
        )
    except Exception as e:
        logger.error(f"Error deleting config {key}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to delete config",
        )


# User management endpoints
@router.get("/users", response_model=UsersListResponse)
async def list_users(
    current_user: Annotated[User, Depends(get_current_superuser)],
    db: Annotated[AsyncSession, Depends(get_db)],
    limit: int = Query(50, ge=1, le=1000, description="Maximum number of users per page"),
    skip: int = Query(0, ge=0, description="Number of users to skip"),
    search: str | None = Query(None, description="Search by email (case-insensitive partial match)"),
) -> UsersListResponse:
    """
    List all users (paginated with search).

    Requires superuser access.
    """
    try:
        # Subqueries for counts to avoid N+1 and cartesian products
        strategy_count_subq = (
            select(func.count(Strategy.id))
            .where(Strategy.user_id == User.id)
            .correlate(User)
            .scalar_subquery()
        )
        ai_report_count_subq = (
            select(func.count(AIReport.id))
            .where(AIReport.user_id == User.id)
            .correlate(User)
            .scalar_subquery()
        )

        # Build base query
        base_query = select(
            User,
            strategy_count_subq.label("strategies_count"),
            ai_report_count_subq.label("ai_reports_count")
        )
        
        # Apply search filter if provided
        if search and search.strip():
            search_term = f"%{search.strip()}%"
            base_query = base_query.where(User.email.ilike(search_term))
        
        # Count total (before pagination) - use scalar_subquery for proper counting
        count_query = select(func.count(User.id))
        if search and search.strip():
            search_term = f"%{search.strip()}%"
            count_query = count_query.where(User.email.ilike(search_term))
        total_result = await db.execute(count_query)
        total = total_result.scalar_one() or 0
        
        # Query users with subqueries for counting
        result = await db.execute(
            base_query
            .order_by(User.created_at.desc())
            .limit(limit)
            .offset(skip)
        )
        rows = result.all()

        return UsersListResponse(
            users=[
                UserResponse(
                    id=row.User.id,
                    email=row.User.email,
                    is_pro=row.User.is_pro,
                    is_superuser=row.User.is_superuser,
                    subscription_id=row.User.subscription_id,
                    plan_expiry_date=row.User.plan_expiry_date,
                    daily_ai_usage=row.User.daily_ai_usage,
                    created_at=row.User.created_at,
                    strategies_count=row.strategies_count,
                    ai_reports_count=row.ai_reports_count,
                )
                for row in rows
            ],
            total=total,
            page=skip // limit if limit > 0 else 0,
            limit=limit,
        )
    except Exception as e:
        logger.error(f"Error listing users: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to list users",
        )


@router.get("/users/{user_id}", response_model=UserResponse)
async def get_user(
    user_id: UUID,
    current_user: Annotated[User, Depends(get_current_superuser)],
    db: Annotated[AsyncSession, Depends(get_db)],
) -> UserResponse:
    """
    Get user details by ID.

    Requires superuser access.
    """
    try:
        strategy_count_subq = (
            select(func.count(Strategy.id))
            .where(Strategy.user_id == User.id)
            .correlate(User)
            .scalar_subquery()
        )
        ai_report_count_subq = (
            select(func.count(AIReport.id))
            .where(AIReport.user_id == User.id)
            .correlate(User)
            .scalar_subquery()
        )

        # Query user with subqueries for counting
        result = await db.execute(
            select(
                User,
                strategy_count_subq.label("strategies_count"),
                ai_report_count_subq.label("ai_reports_count")
            )
            .where(User.id == user_id)
        )
        row = result.first()

        if not row:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="User not found",
            )

        return UserResponse(
            id=row.User.id,
            email=row.User.email,
            is_pro=row.User.is_pro,
            is_superuser=row.User.is_superuser,
            subscription_id=row.User.subscription_id,
            plan_expiry_date=row.User.plan_expiry_date,
            daily_ai_usage=row.User.daily_ai_usage,
            created_at=row.User.created_at,
            strategies_count=row.strategies_count,
            ai_reports_count=row.ai_reports_count,
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error fetching user {user_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to fetch user",
        )


@router.put("/users/{user_id}", response_model=UserResponse)
async def update_user(
    user_id: UUID,
    request: UserUpdateRequest,
    current_user: Annotated[User, Depends(get_current_superuser)],
    db: Annotated[AsyncSession, Depends(get_db)],
) -> UserResponse:
    """
    Update user properties.

    Requires superuser access.
    """
    try:
        result = await db.execute(select(User).where(User.id == user_id))
        user = result.scalar_one_or_none()

        if not user:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="User not found",
            )

        # Update fields if provided
        if request.is_pro is not None:
            user.is_pro = request.is_pro
        if request.is_superuser is not None:
            user.is_superuser = request.is_superuser
        if request.plan_expiry_date is not None:
            user.plan_expiry_date = request.plan_expiry_date

        await db.commit()

        strategy_count_subq = (
            select(func.count(Strategy.id))
            .where(Strategy.user_id == User.id)
            .correlate(User)
            .scalar_subquery()
        )
        ai_report_count_subq = (
            select(func.count(AIReport.id))
            .where(AIReport.user_id == User.id)
            .correlate(User)
            .scalar_subquery()
        )

        # Reload user with subqueries to get counts
        result = await db.execute(
            select(
                User,
                strategy_count_subq.label("strategies_count"),
                ai_report_count_subq.label("ai_reports_count")
            )
            .where(User.id == user.id)
        )
        row = result.first()

        if not row:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="User not found after update",
            )

        return UserResponse(
            id=row.User.id,
            email=row.User.email,
            is_pro=row.User.is_pro,
            is_superuser=row.User.is_superuser,
            subscription_id=row.User.subscription_id,
            plan_expiry_date=row.User.plan_expiry_date,
            daily_ai_usage=row.User.daily_ai_usage,
            created_at=row.User.created_at,
            strategies_count=row.strategies_count,
            ai_reports_count=row.ai_reports_count,
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error updating user {user_id}: {e}", exc_info=True)
        await db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to update user",
        )


@router.delete("/users/{user_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_user(
    user_id: UUID,
    current_user: Annotated[User, Depends(get_current_superuser)],
    db: Annotated[AsyncSession, Depends(get_db)],
) -> None:
    """
    Delete a user and all associated data.

    Requires superuser access.
    
    Prevents deleting yourself.
    """
    try:
        if user_id == current_user.id:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Cannot delete yourself",
            )
        
        result = await db.execute(select(User).where(User.id == user_id))
        user = result.scalar_one_or_none()
        
        if not user:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="User not found",
            )
        
        # Delete associated data first to avoid foreign key constraint violations
        from app.db.models import Strategy, AIReport, GeneratedImage
        
        # Delete user's generated images
        images_result = await db.execute(
            select(GeneratedImage).where(GeneratedImage.user_id == user_id)
        )
        images = images_result.scalars().all()
        for image in images:
            await db.delete(image)

        # Delete user's strategies
        strategies_result = await db.execute(
            select(Strategy).where(Strategy.user_id == user_id)
        )
        strategies = strategies_result.scalars().all()
        for strategy in strategies:
            await db.delete(strategy)
        
        # Delete user's AI reports
        reports_result = await db.execute(
            select(AIReport).where(AIReport.user_id == user_id)
        )
        reports = reports_result.scalars().all()
        for report in reports:
            await db.delete(report)
        
        # Now delete the user (tasks will be deleted by cascade)
        await db.delete(user)
        await db.commit()
        
        logger.info(f"User {user_id} deleted by admin {current_user.id} (deleted {len(images)} images, {len(strategies)} strategies, {len(reports)} reports)")
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error deleting user {user_id}: {e}", exc_info=True)
        await db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to delete user",
        )


